archive = "bionic"
version = "18.04"
origin = "system76"
label = "System76"
email = "info@system76.com"
architectures = [ "amd64" ]
extra_repos = [ "deb http://ppa.launchpad.net/system76/pop/ubuntu bionic main" ]

[[direct]]
name = "code"
version = "1.51.1-1605051630"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/e5a624b788d92b8d34d1392e4c4d9789406efe8f/code_1.51.1-1605051630_amd64.deb"
    checksum = "d101b6ee4445875ee115fd19ad6488a70a0780f12659602229bfb433860823cc"

[[direct]]
name = "discord"
version = "0.0.14"

    [[direct.urls]]
    url = "https://dl.discordapp.net/apps/linux/${version}/discord-${version}.deb"
    checksum = "0c720cfbedf35638f67e52478a7c87ca5ea0e3b17090992b94205c7b2b629ec3"
    arch = "amd64"

[[direct]]
name = "slack-desktop"
version = "4.4.2"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/linux_releases/${name}-${version}-amd64.deb"
    checksum = "5aaa055652155773985c6b2d45b87e6321c1f98213218dfc8e416cbc44043a73"

[[direct]]
name = "spotify-client"
version = "1.1.10.546.ge08ef575-19"

    [[direct.urls]]
    url = "http://repository.spotify.com/pool/non-free/s/${name}/${name}_${version}_amd64.deb"
    checksum = "da49fd4d222ff7d719345fba6298f38a6422ef293bb43ada13cf857a694a12e6"

[[direct]]
name = "signal-desktop"
version = "1.29.6"

    [[direct.urls]]
    url = "https://updates.signal.org/desktop/apt/pool/main/s/signal-desktop/signal-desktop_1.29.6_amd64.deb"
    checksum = "4470b6697a611ed338c1e1e809d0fc713878a97347c5e25df9dd82ed276139e8"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "gitkraken"
version = "current"

    [[direct.urls]]
    url = "https://release.gitkraken.com/linux/${name}-amd64.deb"

[[direct]]
name = "plex-media-server"
version = "1.18.2.2058-e67a4e892"

    [[direct.urls]]
    url = "https://downloads.plex.tv/plex-media-server-new/1.18.2.2058-e67a4e892/debian/plexmediaserver_1.18.2.2058-e67a4e892_amd64.deb"
    checksum = "a48082bce73747257ca754198992214ff3fad805fe989ff2fda46052315f38b1"
