archive = "hirsute"
version = "21.04"
origin = "system76"
label = "System76"
email = "info@system76.com"
architectures = [ "amd64" ]

[[direct]]
name = "discord"
version = "0.0.16"

    [[direct.urls]]
    url = "https://dl.discordapp.net/apps/linux/${version}/discord-${version}.deb"
    checksum = "6db1cd31382d2e1bd12fd74f914b558df28ed99421983c01e1e4fa6cb5f694ca"
    arch = "amd64"

[[direct]]
name = "code"
version = "1.58.2-1626302803"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/c3f126316369cd610563c75b1b1725e0679adfb3/code_1.58.2-1626302803_amd64.deb"
    checksum = "c1fa404ef9c2779449640b071797b82bf159b8f99737b5c4108df945d04ffda5"

[[direct]]
name = "slack-desktop"
version = "4.4.2"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/linux_releases/${name}-${version}-amd64.deb"
    checksum = "5aaa055652155773985c6b2d45b87e6321c1f98213218dfc8e416cbc44043a73"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "plex-media-server"
version = "1.19.1.2701-6327e27bf"

    [[direct.urls]]
    url = "https://downloads.plex.tv/plex-media-server-new/1.19.1.2701-6327e27bf/debian/plexmediaserver_1.19.1.2701-6327e27bf_amd64.deb"
    checksum = "aedee3bf69fc60fd86ca32555ce67ed6bc350d5552fd52df389d36c0b5875155"
