archive = "hirsute"
version = "21.04"
origin = "system76"
label = "System76"
email = "info@system76.com"
architectures = [ "amd64" ]

[[direct]]
name = "code"
version = "1.60.1-1631294805"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/83bd43bc519d15e50c4272c6cf5c1479df196a4d/code_1.60.1-1631294805_amd64.deb"
    checksum = "7606eabb7b38535d6533524876820ed5cdd9b56a47c9d953dd1f3ffcb4aaffbf"

[[direct]]
name = "discord"
version = "0.0.43"

    [[direct.urls]]
    url = "https://dl.discordapp.net/apps/linux/${version}/discord-${version}.deb"
    checksum = "3dca17e6dd70e046fd170b0c996fa6a9776278609ab4a6044b1e4e8e853c8029"
    arch = "amd64"

[[direct]]
name = "slack-desktop"
version = "4.33.90"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/releases/linux/${version}/prod/x64/${name}-${version}-amd64.deb"
    checksum = "54a73d1f85d65c900b2973e7d737a00149d3dad37d9960f9dadff097a2e854dc"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "plex-media-server"
version = "1.19.1.2701-6327e27bf"

    [[direct.urls]]
    url = "https://downloads.plex.tv/plex-media-server-new/1.19.1.2701-6327e27bf/debian/plexmediaserver_1.19.1.2701-6327e27bf_amd64.deb"
    checksum = "aedee3bf69fc60fd86ca32555ce67ed6bc350d5552fd52df389d36c0b5875155"

[[direct]]
name = "vivaldi-stable"
version = "5.6.2867.58-1"

    [[direct.urls]]
    url = "https://downloads.vivaldi.com/stable/${name}_${version}_amd64.deb"
    checksum = "7911d068aced7faea8f45a023524725d2e47b7a779d464e294d3b90f122d502c"
    arch = "amd64"
